### ISSUE TITLE
HidHide understanding question / not working (maybe wrong usage)

### ISSUE THREAD

**Issue by NicciZar** [ViGEm/HidHide#15]
Hello,

I don't really know if I understand the usage of this program..
Does it block the Key-Input from a HID to the system and only allows it to be send (seen) by a Re-Mapper program so I can remap the key to do something else and not do what the original key does?
Or does it just hides the HID to be seen so it cannot be selected as Input device. 

I want to change the HID presses of my secondary Numpad ( I read this Issue: https://github.com/ViGEm/HidHide/issues/4 but I saw that I can disable the "Gaming devices only" option inside the configuration utility and proceeded)

I installed HidHide v.1.0.30.0 -> Reboot -> uncheck the "Gaming Device only" option -> try to write numbers with the selected device inside Editor -> numbers appearing, doesn't seem to be altered at all

Does the statement "Mice and Keyboards are not supported" from the link above still applies to this and all following versions of the program or did it change?

Some Info about the following screenshot:
Is the "HID-compliant consumer control device" meant by HID Keyboard device? Because its the only device that I connected as an HID (Numpad).

![2021-04-25_HidHide_Pic-1](https://user-images.githubusercontent.com/43537611/116000946-895a5780-a5f2-11eb-90df-437a0f7caa03.png)

Best regards

**Comment by nefarius** [comment]
> I don't really know if I understand the usage of this program..

It allows you to control which process (application) can see and therefore use a gamepad/joystick/wheel. Most common use case is you wanna hide a DualShock 4 Controller from the rest of the system **but** allow a remapper tool like DS4Windows to access it, so it in turn can present it to the game as an Xbox controller, avoiding doubled input issues (since in this setup now the system sees 2 devices that act as one).



> I installed HidHide v.1.0.30.0 -> Reboot -> uncheck the "Gaming Device only" option -> try to write numbers with the selected device inside Editor -> numbers appearing, doesn't seem to be altered at all

This checkbox simply "weakens" the device list filter used by the UI program in case it didn't declare a gaming device as such. It doesn't enable any additional driver feature.



> Does the statement "Mice and Keyboards are not supported" from the link above still applies to this and all following versions of the program or did it change?

The statement holds and will not change. This solution is not designed to block keyboards/mice/touchpads so you can't use it for that purpose.


> Some Info about the following screenshot:
> Is the "HID-compliant consumer control device" meant by HID Keyboard device? Because its the only device that I connected as an HID (Numpad).

I can't answer you that, that depends entirely on your hardware.

Hope that could help, cheers.

**Comment by NicciZar** [comment]
Hi

Thank you for the explanation. I will use another application for my desired feature then.

It's still a nice app!

Best regards
